name: Bug Report
description: Report a bug or unexpected behavior
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What is the bug? Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug? Please be sure to provide all links. Provide any relevant IDs such as user ID, list ID, stream ID, campaign ID, etc.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen? Please include screenshots where possible.

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Select the OS where the bug occurred
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser were you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Brave
        - Not Applicable
        - Other
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: Add any relevant logs, screenshots, or error messages. Do not crop screenshots.
